version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3000:3000"
    command: pm2-runtime process.json

  storefront:
    build:
      context: .
      dockerfile: Dockerfile-storefront
      args:
        STOREFRONT_VERSION: 0.1.27
    ports:
      - "4000:4000"
    environment:
      SERVER_API_HOST: https://pohs.cleopatra.quest
      SERVER_API_PORT: 443
      SERVER_API_PATH: shop-api
      
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
