version: '3'
services:
  vendure:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vendure
    user: node
    working_dir: /home/node/app
    volumes: 
      - .:/home/node/app
    ports:
      - "3000:3000"
